services/core/apps/accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"

urlpatterns = [
    path("users/", views.UserListView.as_view(), name="user-list"),
    path("users/<str:pk>/", views.UserDetailView.as_view(), name="user-detail"),
    path("accounts/profile/", views.ProfileView.as_view(), name="profile"),
]

services/core/apps/core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

services/core/myapp/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from accounts.viewsets import UserViewSet

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path("notes/", include("notes.urls")),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("accounts.urls")),
    path("", include("core.urls")),
)

router = DefaultRouter()

router.register(
    "users",
    UserViewSet,
    basename="users",
)

urlpatterns += [
    path("api/v1/", include((router.urls, "api"), namespace="api")),
    path(
        "api/v1/api-auth/", include("rest_framework.urls", namespace="rest_framework")
    ),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/core/templates/myapp/navbars/items/main.html
{% load i18n %}
{% url 'core:home' as the_url %}
<a href="{{ the_url }}" class="navbar-item{% if request.path == the_url %} is-active{% endif %}">
    <span class="icon">
        <i class="fas fa-home"></i>
    </span>
    <span class="ml-1">{% trans 'Home' %}</span>
</a>
{% url 'accounts:user-list' as the_url %}
<a href="{{ the_url }}" class="navbar-item{% if request.path == the_url %} is-active{% endif %}">
    <span class="icon">
        <i class="fas fa-users"></i>
    </span>
    <span class="ml-1">{% trans 'Members' %}</span>
</a>
<a href="{% url 'api:api-root' %}" class="navbar-item">
    <span class="icon">
        <i class="fas fa-globe-europe"></i>
    </span>
    <span class="ml-1">API</span>
</a>